bindet = , H, moveactive, -$window_move_step 0
bindet = , L, moveactive,  $window_move_step 0
bindet = , J, moveactive, 0 $window_move_step
bindet = , K, moveactive, 0 -$window_move_step

bindet = , left, moveactive, -$window_move_step 0
bindet = , right, moveactive,  $window_move_step 0
bindet = , down, moveactive, 0 $window_move_step
bindet = , up, moveactive, 0 -$window_move_step

bind = SHIFT, H, swapwindow, l
bind = SHIFT, L, swapwindow, r
bind = SHIFT, J, swapwindow, d
bind = SHIFT, K, swapwindow, u

bind = SHIFT, left, swapwindow, l
bind = SHIFT, right, swapwindow, r
bind = SHIFT, down, swapwindow, d
bind = SHIFT, up, swapwindow, u
