bind = , J, exec, playerctl play
bind = , K, exec, playerctl pause
bind = , H, exec, playerctl previous
bind = , L, exec, playerctl next

bind = , SPACE, exec, playerctl play-pause

binde = SHIFT, J, exec, playerctl volume 0.01-
binde = SHIFT, K, exec, playerctl volume 0.01+
binde = SHIFT, H, exec, playerctl position 10-
binde = SHIFT, L, exec, playerctl position 10+

bind = , T, exec, playerctl loop Track
bind = , R, exec, playerctl loop Playlist
bind = , Y, exec, playerctl loop None

bind = , S, exec, playerctl shuffle Toggle

# dump info
bind = , D, exec, sh -c "notify-send -u normal \"󰝚 $(playerctl metadata xesam:title)\" \"󰠃 $(playerctl metadata xesam:artist)\n󰎆 $(playerctl metadata xesam:album)\""
