bindet = , H, resizeactive, -$window_resize_step 0
bindet = , L, resizeactive,  $window_resize_step 0
bindet = , J, resizeactive, 0 $window_resize_step
bindet = , K, resizeactive, 0 -$window_resize_step

bindet = , left, resizeactive, -$window_resize_step 0
bindet = , right, resizeactive,  $window_resize_step 0
bindet = , down, resizeactive, 0 $window_resize_step
bindet = , up, resizeactive, 0 -$window_resize_step

bind = , F, fullscreen, 1 toggle
