bind = , H, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -wdirprev $wallpaper_dir
bind = , J, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -wnext $wallpaper_dir
bind = , K, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -wprev $wallpaper_dir
bind = , L, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -wdirnext $wallpaper_dir
bind = , R, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -wrandom $wallpaper_dir
bind = , G, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -wload

bind = SHIFT, J, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -next $wallpaper_dir
bind = SHIFT, K, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -prev $wallpaper_dir
bind = SHIFT, R, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -random $wallpaper_dir
bind = SHIFT, G, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -load $wallpaper_dir

bind = CONTROL, C, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -destroy
