bind = , J, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -next $wallpaper_dir
bind = , K, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -prev $wallpaper_dir
bind = , R, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -random $wallpaper_dir

bind = , G, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -load $wallpaper_dir
bind = SHIFT, G, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -load $wallpaper_dir_animated

bind = SHIFT, J, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -next $wallpaper_dir_animated
bind = SHIFT, K, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -prev $wallpaper_dir_animated
bind = SHIFT, R, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -random $wallpaper_dir_animated

bind = CONTROL, C, exec, ~/.config/hypr/scripts/wallpaper_switch.sh -destroy

bind = , S, exec, swww img $wallpaper
