bind = SHIFT, S, swapactiveworkspaces, current -1
bind = , S, togglespecialworkspace

bind = , J, workspace, -1
bind = , K, workspace, +1
bind = , H, workspace, r-1
bind = , L, workspace, r+1

bind = , down, workspace, -1
bind = , up, workspace, +1
bind = , left, workspace, r-1
bind = , right, workspace, r+1
