windowrule { # moves discord to special workspace
    name = wr-discord-mover
    match:class = discord
    workspace = special:social
}

windowrule { # moves telegram to special workspace
    name = wr-telegram-mover
    match:class = .*telegram.*
    workspace = special:social
}

# maximize suppressor
windowrule {
    name = wr-mx-suppressor
    match:class = .*
    suppress_event = maximize
}
