#!/bin/bash

CACHE_DIR=~/.cache/thinker/swww

e_help() {
    echo -e "usage:\n\t$0 [option] <wallpaper-dir>\noptions:"

    echo -e "\t-help - print this message \n\t-next - chage to next wallpaper \n\t-random (default)- change to random wallpaper\n\t-destroy - remove cache files ($CACHE_DIR)"
}

get_file_list() {
    find "$1" -maxdepth 1 -type f \( \
        -iname "*.jpg" -o \
        -iname "*.jpeg" -o \
        -iname "*.png" -o \
        -iname "*.bmp" -o \
        -iname "*.gif" -o \
        -iname "*.tiff" -o \
        -iname "*.webp" \) -printf "%p\0" | sort -zV | tr '\0' '\n'
}

ch_next() {
    if [[ ! -d $1 ]]; then
        echo "Directory $1 not found."
        return 1
    fi


    FILE_LIST=$(get_file_list $1)
    TOTAL=$(echo -n "$FILE_LIST" | grep -c '^')
    
    if [ "$TOTAL" -eq 0 ]; then
        echo "Error: No image files found in '$1'."
        exit 1
    fi
    
    mkdir -p "$CACHE_DIR"
    
    DIR_HASH=$(echo -n "$1" | md5sum | cut -d' ' -f1)
    STATE_FILE="${CACHE_DIR}/index_${DIR_HASH}"
    
    if [ -f "$STATE_FILE" ]; then
        CURRENT_INDEX=$(cat "$STATE_FILE")
        if ! [[ "$CURRENT_INDEX" =~ ^[0-9]+$ ]]; then
            CURRENT_INDEX=-1
        fi
    else
        CURRENT_INDEX=-1
    fi
    
    NEXT_INDEX=$(( (CURRENT_INDEX + 1) % TOTAL ))
    
    SELECTED_FILE=$(echo "$FILE_LIST" | sed -n "$((NEXT_INDEX + 1))p")
    
    if [ -z "$SELECTED_FILE" ]; then
        echo "Error: Failed to extract file at index $NEXT_INDEX."
        exit 1
    fi
    
    swww img "$SELECTED_FILE" --transition-type random
    
    echo "$NEXT_INDEX" > "$STATE_FILE"
    
    echo "Wallpaper set to: $SELECTED_FILE"
}

ch_random() {
    EXTENSIONS=("*.jpg" "*.jpeg" "*.png" "*.bmp" "*.gif" "*.tiff" "*.webp")
    
    # Сбор всех файлов с указанными расширениями в массиве FILES
    shopt -s nullglob  # Убирает литералы, если ни один файл не подпадает под расширение
    FILES=()
    for ext in "${EXTENSIONS[@]}"; do
        for file in "$WALLPAPER_DIR"/$ext; do
            if [ -f "$file" ]; then
                FILES+=("$file")
            fi
        done
    done
    shopt -u nullglob
    
    # Проверка, что найдено хотя бы одно изображение
    if [ ${#FILES[@]} -eq 0 ]; then
        echo "Error: No image files found in '$WALLPAPER_DIR'."
        exit 1
    fi
    
    # Случайный выбор индекса
    RANDOM_INDEX=$(( RANDOM % ${#FILES[@]} ))
    SELECTED="${FILES[$RANDOM_INDEX]}"
    
    # Установка обоев с помощью swww (с произвольным типом перехода)
    swww img "$SELECTED" --transition-type random
    
    # Информирование пользователя
    echo "Wallpaper set to: $SELECTED"
}

if [[ $# -eq 1 ]]; then
    case $1 in
        "-help") e_help ;;
        "-destroy") purge ;;
        *) e_help ;;
    esac

    exit 0
elif [[ $# -eq 2 ]]; then
    case $1 in
        "-next") ch_next $2 ;;
        "-random") ch_random $2 ;;
        *) e_help ;;
    esac
    
    exit 0
else
    e_help
    exit 2
fi
